version: '3.3'
services:
  postgresql:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - './exercises:/exercises'
