CREATE TABLE categories (
  id integer not null,
  category varchar(255) not null
);

CREATE TABLE posts (
  id integer not null,
  category_id integer not null,
  title varchar(255) not null,
  views integer not null
);

INSERT INTO categories (id,category)
VALUES 
  (1, 'repellendus'),
  (2, 'necessitatibus'),
  (3, 'quis'),
  (4, 'cumque'),
  (5, 'beatae'),
  (6, 'dolorem'),
  (7, 'qui'),
  (8, 'numquam'),
  (9, 'corporis'),
  (10, 'aut');

INSERT INTO posts (id,title,category_id,views)
VALUES 
  (1, 'Voluptatem praesentium consequatur quia eos vitae.', 6, 714),
  (2, 'In veritatis sed voluptas ea quia saepe.', 6, 656),
  (3, 'Non eos aut eaque maiores debitis rerum.', 5, 444),
  (4, 'Unde harum labore nisi corrupti quod animi saepe.', 2, 102),
  (5, 'Sunt voluptas vitae nostrum amet perferendis fuga.', 3, 521),
  (6, 'Sint similique ipsum blanditiis corporis occaecati pariatur earum.', 6, 119),
  (7, 'Quae non voluptatem quis explicabo minima dolorem quos.', 1, 819),
  (8, 'Eum deserunt fugit sunt.', 5, 683),
  (9, 'Tenetur sit nulla animi veniam.', 9, 890),
  (10, 'Dolorum earum eligendi magnam.', 6, 142),
  (11, 'Itaque occaecati consequatur unde dolore quia mollitia fugit tempora.', 1, 193),
  (12, 'Facilis soluta enim odio ut.', 6, 957),
  (13, 'Blanditiis quisquam accusantium illum voluptate.', 10, 277),
  (14, 'Assumenda eveniet omnis sed eius sunt deleniti sint.', 1, 427),
  (15, 'Tempora quibusdam et aut aperiam.', 8, 807),
  (16, 'Temporibus nostrum facilis quo est rerum cupiditate dolores.', 2, 168),
  (17, 'Molestiae nisi libero iusto.', 9, 798),
  (19, 'Consequatur reiciendis aut ut tenetur eveniet recusandae dignissimos.', 10, 367),
  (20, 'Omnis reprehenderit laborum in.', 6, 784),
  (21, 'Aperiam ad eveniet corporis repudiandae.', 1, 982),
  (22, 'Itaque et nesciunt placeat.', 1, 4),
  (23, 'Culpa eaque occaecati sint non.', 6, 57),
  (24, 'Cumque quaerat quidem voluptas eos molestias.', 2, 266),
  (26, 'Modi incidunt excepturi in quasi explicabo.', 6, 149),
  (27, 'Est sit consequatur beatae non et.', 3, 599),
  (28, 'Rerum aut aut eligendi iste qui ut est maiores.', 10, 556),
  (29, 'Mollitia aut error fugiat et vitae id.', 3, 362),
  (30, 'Occaecati magni dicta rerum.', 9, 247),
  (31, 'Repellat inventore ipsam officia eos aut asperiores.', 5, 303),
  (32, 'Laboriosam enim ipsum provident quo.', 9, 892),
  (33, 'Voluptas ut numquam rem minima enim cupiditate aut.', 2, 306),
  (34, 'Aspernatur nostrum reprehenderit molestias.', 10, 713),
  (36, 'Corporis eos placeat labore.', 8, 699),
  (37, 'At autem commodi quas doloribus laboriosam provident minima veritatis.', 3, 534),
  (38, 'Deleniti est ut quia similique et aperiam quisquam est.', 9, 26),
  (39, 'Saepe ipsa nam ut non dignissimos.', 8, 558),
  (40, 'Vero et omnis autem vel iusto.', 8, 98),
  (41, 'Voluptatem aspernatur maxime nobis qui et.', 3, 329),
  (42, 'Aut atque omnis sed tenetur excepturi minima.', 6, 632),
  (43, 'Molestiae asperiores adipisci est id cumque.', 3, 109),
  (44, 'Dolores animi eius veniam aut aut voluptatem.', 10, 592),
  (48, 'Explicabo consectetur nemo at.', 10, 935),
  (49, 'Rerum nemo quis tempora aspernatur consectetur.', 9, 972),
  (50, 'Quo ab quam cum sed repudiandae ad quia et.', 9, 38),
  (51, 'Quaerat mollitia quia nihil id veniam aperiam.', 1, 774),
  (52, 'Quae qui id sunt harum.', 10, 22),
  (53, 'Inventore minima et eum velit quo molestias alias quaerat.', 2, 796),
  (54, 'Aperiam dolor pariatur et iste sed.', 1, 501),
  (56, 'Iusto et tenetur ex consequuntur quia voluptatem.', 3, 882),
  (57, 'Iure et minus doloremque fugit commodi optio corrupti consequatur.', 1, 382),
  (58, 'Ratione in aut modi et sequi illo.', 5, 380),
  (60, 'Et quis aperiam sint consequatur repellendus.', 10, 468),
  (62, 'Aperiam dolores neque illum.', 6, 119),
  (63, 'Amet quod rem natus nihil et.', 3, 633),
  (64, 'Doloremque magnam inventore sit expedita.', 9, 102),
  (65, 'Quia consequatur minus quos eos vel suscipit a.', 8, 3),
  (68, 'Consectetur qui eaque alias corrupti error consequuntur et.', 1, 279),
  (69, 'Consequatur odio molestias tempore alias quibusdam repellat.', 9, 864),
  (70, 'Et molestiae vel et odio et delectus consequatur.', 5, 155),
  (71, 'Eius eum est explicabo non sed delectus maxime.', 3, 304),
  (72, 'Qui reprehenderit inventore ipsam tempora.', 2, 137),
  (73, 'Alias quaerat saepe dolor.', 10, 981),
  (74, 'Non aut nobis sapiente.', 5, 871),
  (76, 'Assumenda quae ipsum aut ipsa.', 9, 238),
  (79, 'Delectus fugit repellat repudiandae.', 10, 669),
  (80, 'Animi eos numquam quia sint in qui distinctio voluptas.', 2, 769),
  (81, 'Quia nesciunt reiciendis ipsum quasi.', 5, 272),
  (82, 'Autem commodi quaerat facilis omnis quia ipsum.', 2, 150),
  (83, 'Quam reiciendis ipsam minima quia saepe in cumque.', 10, 35),
  (84, 'Quisquam quia neque sapiente et sed.', 2, 600),
  (86, 'Eius animi odit quaerat neque.', 1, 557),
  (87, 'Temporibus possimus voluptatibus aut ut est quae cupiditate aliquam.', 5, 493),
  (88, 'Deleniti molestiae dicta dolores laboriosam maxime reiciendis tempora.', 9, 488),
  (89, 'Et temporibus amet maiores vero quisquam aut nihil iste.', 8, 303),
  (90, 'Voluptate a ut quo dolores velit eos aut.', 3, 625),
  (91, 'Voluptatum nam placeat officia natus quibusdam.', 3, 181),
  (93, 'Ut vero culpa dolorem.', 8, 862),
  (94, 'Repellat vero perspiciatis explicabo nesciunt ut molestiae accusamus.', 3, 930),
  (95, 'Accusamus quis aspernatur modi aliquid.', 2, 834),
  (96, 'Optio qui consequatur maxime.', 1, 785),
  (98, 'Omnis aut aperiam beatae omnis nihil.', 8, 715),
  (100, 'Qui earum illo iusto natus assumenda.', 10, 666),
  (101, 'Nihil corrupti quam officiis cupiditate est.', 7, 646),
  (102, 'Esse pariatur omnis incidunt qui quibusdam quia eum.', 7, 646),
  (103, 'Dolores et quibusdam quam nulla dignissimos neque.', 7, 646);
