CREATE OR REPLACE FUNCTION weekdays(DATE1 DATE, DATE2 DATE) RETURNS INTEGER
AS $$
DECLARE
  TMP_DATE DATE;
  NUMBER_OF_WEEKS INTEGER;
  COUNTER INTEGER;
  DOW INTEGER;
BEGIN
  IF(DATE1 > DATE2) THEN
    TMP_DATE := DATE1;
    DATE1 := DATE2;
    DATE2 := TMP_DATE;
  END IF;
  NUMBER_OF_WEEKS := (date2 - date1)/7;
  COUNTER := NUMBER_OF_WEEKS*5;
  FOR i IN NUMBER_OF_WEEKS*7..date2-date1 LOOP
    DOW := EXTRACT(ISODOW FROM (DATE1+i));
    IF(DOW != 6 AND DOW != 7) THEN
      COUNTER := COUNTER + 1;
    END IF;
  END LOOP;
  RETURN COUNTER;
END; $$ LANGUAGE plpgsql;
