CREATE TABLE categories (
  id SERIAL PRIMARY KEY,
  category VARCHAR(255) NOT NULL
);

CREATE TABLE posts (
  id SERIAL PRIMARY KEY,
  category_id INTEGER,
  title VARCHAR(255) NOT NULL,
  views INTEGER NOT NULL,
  CONSTRAINT fk_categories FOREIGN KEY(category_id) REFERENCES categories(id)
);

INSERT INTO categories(id, category)
VALUES
  (1,'et'),
  (2,'optio'),
  (3,'omnis'),
  (4,'ea'),
  (5,'sint'),
  (6,'enim'),
  (7,'consectetur'),
  (8,'iure'),
  (9,'et'),
  (10,'soluta');

INSERT INTO posts (id, title, category_id, views)
VALUES
  (1,'Id ratione quisquam quibusdam ut.',7,438),
  (2,'Aspernatur quo enim et sint id expedita quisquam.',1,382),
  (3,'Unde soluta fugiat iusto odit optio aspernatur dolore voluptatem.',6,925),
  (4,'Et nemo in odit.',6,852),
  (5,'Unde consectetur sit itaque.',4,313),
  (6,'Eos nemo aliquam enim quis natus maiores magni ut.',8,123),
  (7,'Veniam accusantium fugit unde at mollitia qui dolor nostrum.',5,157),
  (10,'Sit qui minus est maxime.',8,173),
  (11,'Dolores laborum impedit alias non.',8,174),
  (13,'Dolores architecto ea accusamus ipsam omnis.',10,826),
  (14,'Placeat dolorem dignissimos aperiam velit in quibusdam.',5,237),
  (15,'Esse at officia qui cupiditate nostrum ut quasi iste.',5,184),
  (16,'Corporis impedit et ut consequatur rerum ad non.',1,658),
  (17,'Molestiae consequatur ut dolores sapiente.',7,426),
  (18,'Repudiandae eos tempora soluta iusto quidem.',7,564),
  (19,'Sunt velit reiciendis deserunt corporis.',5,471),
  (20,'Nulla eveniet pariatur et enim inventore repellendus est.',1,223),
  (21,'Dolores modi neque architecto.',10,344),
  (22,'In molestiae eum dolores maiores sed sequi eos.',4,347),
  (23,'Voluptas consequatur quia repudiandae in optio.',6,123),
  (25,'Corrupti ratione tenetur facilis doloribus dolores sunt.',8,253),
  (27,'Nemo iure sapiente tempora maiores illo ullam doloribus.',2,401),
  (30,'Id ut dolorem dolore unde.',10,583),
  (31,'Sit animi adipisci iure eius.',5,971),
  (33,'In nihil explicabo sunt.',7,692),
  (34,'Provident rem et nam sed odit exercitationem doloribus sequi.',10,572),
  (35,'Illo earum cumque porro vel.',2,285),
  (36,'Tempore eos asperiores dolor tempora qui voluptatem vero aliquam.',5,414),
  (37,'Rerum nostrum corrupti nulla aut recusandae sed.',10,311),
  (38,'Et earum assumenda autem sint iste incidunt nihil.',7,271),
  (40,'Magnam aut at possimus.',8,882),
  (41,'Perspiciatis labore rem sed deleniti.',10,228),
  (42,'Unde nemo sint iure fugiat qui est et libero.',10,442),
  (43,'Voluptatem dolores officiis temporibus.',7,938),
  (44,'Aut error animi eligendi quia.',4,732),
  (45,'Placeat accusantium ut est.',1,461),
  (46,'Iusto quisquam iure et facilis dignissimos aut et quod.',7,203),
  (47,'Voluptate dicta eligendi eum.',4,217),
  (48,'Et culpa aperiam eaque quia fugiat nihil.',6,902),
  (49,'Ea voluptatem tempore aspernatur.',5,834),
  (50,'Expedita iure quae quos sequi fugit.',6,981),
  (51,'Accusantium qui aut eos doloremque.',10,610),
  (52,'Quia aut omnis quis.',10,495),
  (53,'Et aut ut ullam.',8,938),
  (54,'Accusantium debitis quis dolor quos qui voluptatum fugit.',7,589),
  (55,'At nemo tempora aut vitae ipsum nisi et.',1,579),
  (56,'Sit incidunt omnis blanditiis.',10,896),
  (57,'Eligendi aut qui doloribus fuga.',1,2),
  (58,'Omnis distinctio accusantium non quos rerum fugit.',1,935),
  (59,'Quos doloribus laborum debitis quia quo blanditiis.',1,168),
  (60,'Consequuntur pariatur est dolorum nostrum repellendus tempora.',1,98),
  (61,'Vel iure eos in harum.',4,57),
  (62,'Ab doloremque consequuntur quia aut nihil omnis.',5,365),
  (63,'Suscipit nulla magni provident dolor.',1,194),
  (64,'Voluptate tenetur et qui fugit omnis labore.',1,479),
  (66,'Illum sunt consequuntur facere tenetur dolores.',6,691),
  (67,'Quidem aut enim sit.',1,979),
  (69,'Velit nostrum ducimus quia veritatis et aut aut repellat.',10,775),
  (71,'Autem autem veritatis libero sed quisquam dolorum corporis cupiditate.',2,311),
  (72,'Qui qui vel et est ut.',5,142),
  (74,'Illum laudantium eos porro animi repellendus culpa explicabo perspiciatis.',1,701),
  (75,'Dolorum velit quibusdam accusantium enim.',1,605),
  (76,'Eum corporis aut consectetur odio.',4,323),
  (77,'Recusandae totam quod ipsam.',5,880),
  (78,'Deserunt vitae optio distinctio voluptatibus officiis consequatur.',8,787),
  (79,'Dolor id distinctio totam at.',1,744),
  (81,'Atque repellat a ratione est ut.',4,752),
  (82,'Aut amet consequuntur assumenda dolorem nihil corrupti.',10,147),
  (85,'Eligendi consequatur distinctio sint vero.',8,213),
  (86,'Aliquid odit officiis illo nemo consequatur harum.',5,27),
  (87,'Vel in illum qui dicta dolores.',7,646),
  (88,'Qui id nobis officiis ut.',7,184),
  (89,'Occaecati molestiae officia nulla voluptatem ipsum.',10,478),
  (90,'Omnis harum fugiat officia deserunt facilis.',4,913),
  (91,'Ut sint quia nobis labore et numquam iste officiis.',6,237),
  (92,'Labore error ad qui officiis atque necessitatibus ut et.',10,379),
  (93,'In impedit sit dolore assumenda vitae.',7,823),
  (95,'Molestias consequuntur nemo aspernatur dicta eius facere aut sint.',1,46),
  (97,'Nisi aut itaque est voluptatem omnis.',1,753),
  (98,'Voluptates tempore numquam consequatur.',4,58),
  (99,'Quisquam tempore est aliquid officia eaque maiores sapiente.',10,147),
  (100,'Ut error dolor velit.',2,990),
  (101,'Id aut asperiores minus.',9,827),
  (102,'Id sit minus sit consequatur et eum aut.',9,827),
  (103,'Perspiciatis sequi aut rem qui minus quasi eveniet ea.',9,827);
